services:
  # Service 1: PostgreSQL
  postgres:
    image: postgres:18
    container_name: velib-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=velib_raw_db
    ports:
      - "5432:5432"
    volumes:
      - "./dataLake:/var/lib/postgresql/data:rw"
      # Hint: ./sql/init.sql peut être utile
    # VOUS : ajouter healthcheck ?

  # Service 2: JupyterLab
  jupyter:
    image: jupyter/base-notebook  # VOUS : quel type ? (scipy, pyspark, datascience)
    container_name: velib-jupyter
    ports:
      - 8889:8888
    volumes:
      - ./notebooks:/home/jovyan/work
      # VOUS : où partager les données avec postgres ?
    command: start-notebook.py --NotebookApp.token='my-token'
    # VOUS : dépend de postgres ?

  # Service 3 (optionnel): pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./sql:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"