services:

  postgres:
    image: postgres:18
    container_name: velib_postgres
    environment:
      POSTGRES_USER: velib
      POSTGRES_PASSWORD: velib
      POSTGRES_DB: velib_dw
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  spark:
    image: apache/spark:3.5.0
    container_name: velib_spark
    volumes:
      - ../data_lake:/opt/data_lake
      - ../spark_jobs:/opt/spark_jobs
    ports:
      - "8080:8080"

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: velib_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../data_lake:/home/jovyan/data_lake
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=velibexplo
    depends_on:
      - postgres
      - spark

  ingestion:
    build: ../ingestion
    container_name: velib_ingestion
    volumes:
      - ../data_lake:/app/data_lake
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: velib_airflow_web
    depends_on:
    - airflow-scheduler
    - postgres
    environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://velib:velib@postgres:5432/velib_dw
    - AIRFLOW__CORE__FERNET_KEY=fernetkey123
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "8081:8080"


  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: velib_airflow_scheduler
    depends_on:
    - postgres
    environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://velib:velib@postgres:5432/velib_dw
    - AIRFLOW__CORE__FERNET_KEY=fernetkey123
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pg_data:
