FROM python:3.12-slim

WORKDIR /app

COPY scripts/cleanup_parquet/requirement_cleanup.txt .

RUN pip install --no-cache-dir -r requirement_cleanup.txt

COPY scripts/cleanup_parquet/cleanup_parquet.py /app/cleanup_parquet.py

ENTRYPOINT ["python", "/app/cleanup_parquet.py"]
